name: Deploy IT Dashboard to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3️⃣ Install dependencies (if any)
      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm ci
          else
            echo "No package.json found, skipping npm install"
          fi

      # 4️⃣ Build (if needed)
      - name: Build project
        run: |
          if [ -f "package.json" ]; then
            npm run build || echo "No build script found, skipping build"
          else
            echo "No package.json found, skipping build"
          fi

      # 5️⃣ Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'

      # 6️⃣ Notify success
      - name: Deployment complete
        run: |
          echo "✅ IT Dashboard deployed successfully to Vercel!"
          echo "🌐 Live at: https://it-dashboard-prod.vercel.app/"
          echo "📊 Connected to Microsoft 365 with real data"
