name: Deploy IT Dashboard to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Connect to your Hostinger VPS via SSH
      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "🔄 Updating live dashboard..."
            cd /var/www/it-dashboard

            # Pull latest changes
            git fetch origin main
            git reset --hard origin/main

            # Optional: ensure permissions are correct
            chown -R root:root /var/www/it-dashboard
            chmod -R 755 /var/www/it-dashboard

            # Run footer fix after deployment
            if [ -f "/var/www/it-dashboard/fix-footer.sh" ]; then
              bash /var/www/it-dashboard/fix-footer.sh
            else
              echo "⚠️ fix-footer.sh not found, skipping footer update."
            fi

            # Reload Nginx to apply updates
            systemctl reload nginx

      # 3️⃣ Notify success
      - name: Deployment complete
        run: echo "✅ IT Dashboard deployed successfully with Savio branding!"
